spring.application.name=indy-wallet
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/indy-wallet

spring.datasource.url=jdbc:postgresql://localhost:5432/indywallet
spring.datasource.username=indy
spring.datasource.password=indy123
spring.jpa.hibernate.ddl-auto=update

spring.profiles.include=local

mtsocket.api.url=http://localhost:81

investment.tracking.enabled=false
